# Generated by Django 5.0.4 on 2024-05-06 18:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mainapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(to="mainapp.client"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="first_send",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
