# Generated by Django 5.0.4 on 2024-05-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("content", models.TextField(verbose_name="Содержание")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog_images/",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "views",
                    models.PositiveIntegerField(
                        blank=True, default=0, null=True, verbose_name="Просмотры"
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата публикации"
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
